language: java

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
  - openjdk7

matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
      env: CUSTOM_MVN_VERION="3.2.5"

install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      if [[ "${CUSTOM_MVN_VERION}" == "3.0" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1;
      else
        wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      fi;
      unzip -qq apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      export M2_HOME=$PWD/apache-maven-${CUSTOM_MVN_VERION};
      export PATH=$M2_HOME/bin:$PATH;
      mvn -version;
    fi
  - mvn test -DskipTests=true -B -V
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
  - jdk_switcher use $TRAVIS_JDK_VERSION
